sphinx_autodoc_typehints.py

In this case with at least Python 3.4.3:
```
class Foo(object):
@staticmethod
def bar(*args):
"""Some docs"""
```
There is 
```
Exception occurred:
File "/Users/anti1869/Sites/video/venv-v/lib/python3.4/site-packages/sphinx_autodoc_typehints.py", line 49, in process_signature
del argspec.args[0]
IndexError: list assignment index out of range
```
As you can see from the trace, ``args`` is empty in ``FullArgSpec``.
```FullArgSpec(args=[], varargs='args', varkw=None, defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})```
So I decided to add simple check.

Fixed IndexError when using @staticmethod with *args combination

---

sphinx_autodoc_typehints.py
test_sphinx_autodoc_typehints.py

Even thought it's debatable if it makes sense to have a union of a type other than ``Any`` and ``Any``, I came across it and encountered the error:
```
File "/home/python/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 695, in add_content
for i, line in enumerate(self.process_doc(docstrings)):
File "/home/python/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 657, in process_doc
self.options, docstringlines)
File "/home/python/lib/python3.6/site-packages/sphinx/application.py", line 551, in emit
results.append(callback(self, *args))
File "/home/python/lib/python3.6/site-packages/sphinx_autodoc_typehints.py", line 144, in process_docstring
formatted_annotation = format_annotation(annotation)
File "/home/python/lib/python3.6/site-packages/sphinx_autodoc_typehints.py", line …
```

check for "__qualname__" attribute existence on union with ``Any``

---

sphinx_autodoc_typehints.py
test_sphinx_autodoc_typehints.py

If a project is using an explicit sphinx default domain, then the inserted :class: and :data: wind up being not found. Since this is an extension specifically for annotating python code, be explicit with the directives adding a :py: domain prefix to them.

Add explicit py domain to added directives

---

tests/conftest.py

This PR guarantees that the dummy project is removed from the temporary directory area at the start of each test tun.

Remove dummy project from temp on each test run.

---

sphinx_autodoc_typehints.py

The usual recommendation of ordering the return and rtype directives is
the return directive, then the rtype directive.
Previously, if users followed this recommendation, then an additional
rtype directive would be added before the return directive, resulting in
the return type showing twice in the resulting docs.

Avoid adding rtype directive if specified after return

---

sphinx_autodoc_typehints.py
tests/roots/test-dummy/conf.py

Adds a blank line before :rtype: when it is appended. This ensures that
Sphinx doesn't interpret it as part of normal text.
I've only reproduced the problem when using sphinx.ext.napoleon (just
having it loaded is enough; one doesn't need to use numpydoc
formatting), so it's added to the test suite.

Fix for :rtype: being rendered in text

---

setup.cfg
sphinx_autodoc_typehints.py

Fixes issue  #51 "formatargspec is deprecated"
All tests pass.

Fix Sphinx deprecation warning: use "Signature" instead of "formatargspec"

---

setup.cfg
sphinx_autodoc_typehints.py
tests/test_sphinx_autodoc_typehints.py

Fix the following exception during doc builds
```
Exception occurred:
File "/path/to/.venv/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 119, in format_annotation
extra = '\\[{}]'.format(', '.join(format_annotation(param) for param in params))
TypeError: 'NoneType' object is not iterable
```
```
#
#
Traceback (most recent call last):
File "/path/to/.venv/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
app.build(args.force_all, filenames)
File "/path/to/.venv/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
self.builder.build_update()
File "/path/to/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
len(to_build))
File "/path/to/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.p …
```

Fix 'NoneType' object is not iterable on Generics

---

sphinx_autodoc_typehints.py
tests/test_sphinx_autodoc_typehints.py

Resolves #41 producing output of the form `NewType(NewName, OldType)` with appropriate references.

Identify typing.NewType wrappers and construct annotation references

---

sphinx_autodoc_typehints.py
tests/roots/test-dummy/dummy_module.py
tests/test_sphinx_autodoc_typehints.py

a pull request for #31
When such wrong callables found, this ignore them and prints a warning which recommends `functools.wraps`.

Ignore callables defined as local functions

---

setup.cfg
sphinx_autodoc_typehints.py
tests/roots/test-dummy/dummy_module.py
tests/roots/test-dummy/index.rst
tests/test_sphinx_autodoc_typehints.py

Fix #13
I've made it so that there's as little risk of regression as possible for existing users by shortcutting to `get_type_hints` or `__annotations__` if that approach works. If those return empty mappings, use `typed_ast` with `inspect.getsource` to get type hint comments. An additional advantage is that `typed_ast` is only an optional dependency just for type hint comments.

feat: Add type hint comment support

---

README.rst
sphinx_autodoc_typehints.py
tests/test_sphinx_autodoc_typehints.py

When rendering the type hints, add a flag to allow them to always be displayed fully qualified (module + class name).
I have a lot of type hints that belong to external modules, like `aiohttp.Request` or `databaseprovder.Session` and it's much easier to tell what's going on when they render as `aiohttp.Request` instead of `Request`.
Since not everyone may want this, I added a new flag `typehints_fully_qualified` to enable this behaviour.

Allow fully qualified class names

---

sphinx_autodoc_typehints.py

There's an [upstream issue](https://github.com/python/typing/issues/574) which is causing documentation building to fail when recursive type definitions are used. This catches `RecursionError` exceptions when calling `typing.get_type_hints()` so that the build can proceed.
Closes #91

Catch recursion errors when getting type hints

---

sphinx_autodoc_typehints.py
tests/roots/test-dummy/dummy_module.py
tests/test_sphinx_autodoc_typehints.py

This fixes it by collecting them in the correct order. Validated with my project of 250+ type annotated functions.

Default values mess up type comment argument detection

---

README.rst
sphinx_autodoc_typehints.py

If typehints_document_rtype=False (default True), never add an :rtype: directive.
Closes #106.

Introduce typehints_document_rtype config.

---

sphinx_autodoc_typehints.py

The sphinx.util.inspect.Signature api has been deprecated since sphinx
2.4 and is staged for removal in the 4.0 release. [1] This commit updates
the usage to use the alternative function for it that is not
deprecated (and returns a inspect.Signature object from stdlib). This should
avoid raising a deprecation warning on each function signature that is using
typehints.
Fixes #133
[1] https://www.sphinx-doc.org/en/latest/extdev/deprecated.html?highlight=signature

Remove use of sphinx's Signature class

---

setup.cfg
tests/test_sphinx_autodoc_typehints.py

Tests are failing on the `master` branch for this repository.
This is because Sphinx changed in `3.2.0`.
The test changed here (`test_sphinx_output`) relies on the old Sphinx behaviour.
The changes here are for parts of the document not modified by this package.

Fix sphinx expected output test

---

sphinx_autodoc_typehints.py
tests/test_sphinx_autodoc_typehints.py

Sorry this took so long.
Closes #150
I don't think the test failures are related to this change. Seems to be something to do with Python's name mangling.

Change formatting of 'None'.

---

sphinx_autodoc_typehints.py
tests/conftest.py
tests/roots/test-dataclass/conf.py
tests/roots/test-dataclass/dataclass_module.py
tests/roots/test-dataclass/index.rst
tests/roots/test-dummy/dummy_module.py
tests/test_dataclass_py36.py
tests/test_sphinx_autodoc_typehints.py

The existing unit tests appear to catch this regression when running with a python version that exhibits this change, so I didn't add an additional protection.
Please let me know I'm missing anything in this patch. Thanks for a great tool!

Update special dataclass handling

---

CHANGELOG.md
README.md
src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-dummy/dummy_module_simple.py
tests/roots/test-dummy/simple.rst
tests/test_sphinx_autodoc_typehints.py
whitelist.txt

Supersedes #103, fixes #48
In the previous PR, I added them to types, this time I’m adding it to the string. I think both have arguments pro and contra. Should it be configurable?

Add defaults

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

Fixed normalize_source_lines messing with the indentation of method with decorator that has parameter starting with `def`.
`normalize_source_lines` was breaking a method like the following:
```python
@_with_parameters(
_Parameter("self", _Parameter.POSITIONAL_OR_KEYWORD),
*_proxy_instantiation_parameters,
_project_id,
_Parameter(
"node_numbers",
_Parameter.POSITIONAL_OR_KEYWORD,
default=None,
annotation=Optional[Iterable[int]],
),
)
def __init__(bound_args):  # noqa: N805
...
```
Note the decorator parameter `default=None,` starts with `def` and confuses the function.
I got to this fix from #139.

Fixed normalize_source_lines messing with the indentation of method

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py
whitelist.txt

Fixes #197 by just not adding defaults if none can be derived.
The pre-commit failure is because the added branching pushed `process_docstring` over the complexity limit. @gaborbernat I think as the maintainer you should decide how to make it less complex.

Robustly handle signatures

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py
whitelist.txt

https://github.com/tox-dev/sphinx-autodoc-typehints/commit/8dc8d94912431fa79a13f39d7570637244ac1a01 introduced an issue where a bound method with a type hint on the first argument would raise a KeyError looking up the default because that argument isn't present in the signature. This PR simply ignores those parameters.

Fix KeyError with type hints on the first arg of bound methods

---

CHANGELOG.md
setup.cfg
src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-resolve-typing-guard/conf.py
tests/roots/test-resolve-typing-guard/demo_typing_guard.py
tests/roots/test-resolve-typing-guard/index.rst
tests/test_sphinx_autodoc_typehints.py
whitelist.txt

Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>

Resolve type guard imports

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

Resolves https://github.com/tox-dev/sphinx-autodoc-typehints/issues/203

Fix fully_qualified should be typehints_fully_qualified

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-resolve-typing-guard/demo_typing_guard.py

Hi, thanks for your work on this plugin! We're having some problems with [returns](https://github.com/dry-python/returns) because we use type guards inside some classes like [here](https://github.com/dry-python/returns/blob/master/returns/primitives/hkt.py#L92) which leads in some warnings while building sphinx broking our builds:
```text
WARNING: Failed guarded type import with AttributeError('__globals__')
```
This PR fixes that issue, basically when a class object doesn't have the `__globals__` attribute so we basically can call `exec` without the globals if the given object doesn't have the mentioned attribute.

Prevents reaching inner blocks that contains `if TYPE_CHECKING`

---

README.md

It appears that pepy no longer supports the `month` endpoint, it 404s.

ADMIN: Update pepy.tech link in badge

---

README.md
src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-dummy/dummy_module_simple_no_use_rtype.py
tests/roots/test-dummy/simple_no_use_rtype.rst
tests/test_sphinx_autodoc_typehints.py
tox.ini

This fixes an interoperability issue with `sphinx.ext.napoleon`. See issue and code for details.
There is a string-matching aspect to this (see comment in code) that I am not happy with. Is there a better solution? Note that this potentially brittle behavior would only occur if this new option is explicitly disabled, i.e., it should not break existing behavior.
Fixes #217.

Add `typehints_use_rtype` option

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-resolve-typing-guard/demo_typing_guard.py
tests/roots/test-resolve-typing-guard/demo_typing_guard_dummy.py
tests/test_sphinx_autodoc_typehints.py

This PR solves an issue where a mocked module is imported in a module, which is in turn a type guarded import:
module_b:
```python
from viktor import AI  # 'viktor' part of autodoc_mock_imports
...
```
module_a:
```python
if TYPE_CHECKING:
from module_b import ...
```

Fix mock imports on guarded imports

---

.github/workflows/check.yml
CHANGELOG.md
README.md
setup.cfg
src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-dummy/dummy_module.py
tests/test_sphinx_autodoc_typehints.py
tox.ini

https://github.com/python/typing/issues/275

Check 3.11 support

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

Closes #223. This is simple approach that uses string of forward reference and avoids needing to evaluate recursive/mutually recursive type aliases.
I've added two test cases that use recursive aliases and previously would crash. I've also been using this fork for a while in company internal codebase and it's worked well for our recursive annotations.

Add support for recursive type hints

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

The names may have an origin that's not typing, causing an incorrect
role to be applied to them
fixes: #237

only convert role for pydata annotations if module is typing

---

CHANGELOG.md
pyproject.toml
src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py
tox.ini

Adds support for ParamSpec, to keep compat I've decided to only check the name as typing_extensions is not a normal dep, and someone else using the name seems unlikely, though a check for some attribute could be added if necessary

Add support for paramspec

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-dummy/dummy_module.py
tests/roots/test-dummy/index.rst
tests/test_sphinx_autodoc_typehints.py

allow starred args and kwargs in docstring params

---

.pre-commit-config.yaml
pyproject.toml
tox.ini

Fix the CI

---

.gitignore
README.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

I was using this library and noticed that there was no existing way to retain the typehints automatically generated by autodoc in function/class/method signatures. I quite liked the way that return types are annotated with the -> in signatures and wanted to preserve those while using autodoc-typehints.
This pull request adds 2 simple options that **do not alter the behaviour of anyone already using typehints**:
1. `typehints_use_signature` (`False` by default)
2. `typehints_use_signature_return` (`False` by default)
By setting these, the `sph_signature.replace()` commands in `process_signature()` can be altered
With default options:
With the new options set to `True`:

Added options to retain original typehints in signatures

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

This is not super important, but when converting `| None` to `Optional` the code sets the role incorrectly to `class` and so generates dead links.

Set role to data when creating an Optional from `| None`

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

This is a pretty minor change, but I think it improves the visual consistency of the types.

Put Literal args in code blocks

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

typing.Callable is deprecated in favor of collections.abc.Callable since Python 3.9:
https://docs.python.org/3/library/typing.html?highlight=typing%20callable#typing.Callable
This fixes the rendering to look correct regardless of which `Callable` annotation you use.

Handle collections.abc.Callable as well as typing.Callable

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py
whitelist.txt

Remove redundant return type for attributes

---

src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-dummy/dummy_module.py
tests/roots/test-dummy/index.rst
tests/test_sphinx_autodoc_typehints.py

Sometimes a function's documentation will contain a section like 'Usage' or 'Examples', warnings about edge cases, etc. These sections are introduced with a `.. directive::`. This makes it so that sphinx-autodoc-typehints inserts the return type ahead of these sections, rather than after them.

Put rtype before examples or usage section

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

Most of the io module is implemented in the private C extension module called _io. It would be friendly if Python set the module name to io to match the way it is documented but they don't.
I'm not sure how much it is desirable to add a bunch of module name redirects here. Also, perhaps it would be useful to have a configuration option that allows specifying more module redirects since reexporting classes is pretty common.

If module is _io, use io instead

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py
whitelist.txt

The `types` module has a bunch of things like `ModuleType`: `ModuleType.__module__` is
"builtins" and `ModuleType.__name__` is "module", but it should be referenced as `types.ModuleType`.
To deal with these, I made a dict of values exported from `types` to the export name. If an annotation
is in this dict, we use "types" as the module and the reported name as the name.
I also made a couple of nonfunctional changes: 
1. I think `_is_newtype` is more readable as a separate method so I factored it out.
2. `test_parse_annotation` displays more useful error messages if we assert two tuples are equal than if we make three sequential assertions -- this way we can see if more than one are wrong.

Handle types from types module

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

If the `:rtype:` field is being inserted immediately before a directive, we must ensure there is a blank line between the two to avoid a Sphinx warning.
Given that #290, which added this behaviour, already added a suitable test that emits a warning that doesn't fail the suite, I wasn't clear on how best to add a further test for this.
Fix #293.

Fix spacing between `:rtype:` and directives

---

src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-dummy/dummy_module.py
tests/roots/test-dummy/index.rst
tests/test_sphinx_autodoc_typehints.py
whitelist.txt

See the explanation in the diff and in issue #296.

Add fix for #296

---

src/sphinx_autodoc_typehints/__init__.py
src/sphinx_autodoc_typehints/attributes_patch.py
tests/roots/test-dummy/dummy_module.py
tests/roots/test-dummy/index.rst
tests/test_sphinx_autodoc_typehints.py
whitelist.txt

Resolves #298.
This is a bit hard to do because autodoc doesn't emit any events to help us adjust the type rendering for attributes and because the type annotation is currently converted to text and then rendered from text by the `PyAttribute` directive.
The system in autodoc for attribute rendering is:
1. In `AttributeDocumenter.get_directive_header`, call `stringify_annotation` to render the annotation to a string
2. add `:type: stringified annotation` to the directive header of `PyAttribute`
3. When `sphinx.domains.python.PyAttribute` sees the `:type:` it calls `format_annotation` which attempts to convert the string representation of the type into a more fancy representation with cross referencing
Notes:
2. we don't get an opportunity to adjust the directive header with …

Use format_annotation to render class attribute type annotations

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-dummy/dummy_module.py
tests/roots/test-dummy/index.rst
tests/test_sphinx_autodoc_typehints.py
whitelist.txt

The current strategy to place the rtype is still not fully satisfactory on my own documentation. I think this improves it to avoid any need for fudging.
1. If there is an existing :rtype: don't add another
2. If there is a :returns: anywhere, either add directly before it or modify the :returns: line as appropriate
3. If there is a block of :param: documentation, add directly after this
4. If there is a .. directive, add before the directive
5. Add at the end
Step 4 could be refined further, we would really only like to break at directives that introduce headings.
Since it is very hard to decide where the :param: block ends based on directly analyzing the text so I parse the docstring into a docutils tree. From the tree it is not too hard to work out what we need to know.

Improvements to the location of the return type

---

src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-dummy/dummy_module.py
tests/roots/test-dummy/index.rst
tests/test_sphinx_autodoc_typehints.py

Resolves #302.
This increases the robustness of the handling of the docutils tree. The docutils rst parser seems to have a bunch of bugs / shortcomings. The original problem was that several list types do not get their line number set. So to find the line number of a node, if the node itself has None as the line number, we descend through the first children of the node until we find one with a non-None line number.

More robust determination of rtype location / fix issue 302

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_integration.py

Apparently we need to subtract 3 here?
Resolves #305.

Resolve issue 305

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_integration.py

This function never does the correct thing and even if it did the correct thing it would be a problem for us because the rendered type annotation isn't processed by `sphinx-autodoc-typehints`.
Resolves #308

Disable GoogleDocstring._lookup_annotation

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_integration.py
whitelist.txt

If there is no explicitly provided return type, napoleon will incorrectly parse the entire return type explanation. It can be fixed by inserting a line with a single colon at the beginning of the returns section.

Fix napoleon handling of numpy docstrings with no explicitly provided return type

---

src/sphinx_autodoc_typehints/__init__.py
src/sphinx_autodoc_typehints/patches.py

NFC: Move patches to a separate file

---

src/sphinx_autodoc_typehints/__init__.py
src/sphinx_autodoc_typehints/patches.py
tests/test_integration.py
whitelist.txt

This resolves #312. 
The missing line numbers make it impossible for us to correctly calculate where to place the rtype.
See upstream issue:
https://sourceforge.net/p/docutils/bugs/465/
I submitted a patch to docutils to fix these things but it is currently waiting to get through a spam filter. The docutils test suite has no coverage checking whether this field is filled correctly.

Patch docutils rst parser to add line numbers to more nodes

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py

in #9 parallel reading was enabled. Now lets do the same for writing. I've tested this with my (large) project locally. The output looks sane and the total build time was cut in half.

Enable parallel write

---

CHANGELOG.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

Attempt to fix #318.
The access to `_TYPES_DICT` should be wrapped so the error for unhashable type is captured.
This is just a quick hack that fixes the issue for me and there sure is a more elegant way of doing it ...

FIX TypeError: unhashable type

---

pyproject.toml

Remove dependency on itself from pyproject.toml

---

README.md
pyproject.toml

Drop typed-ast as is no longer maintained/used

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_integration.py
tests/test_sphinx_autodoc_typehints.py

Resolves issue #395.
Here's a screenshot where I've used this in Pyodide's docs to add some ugly css to the types:

ENH Add a css wrapper to generated types

---

src/sphinx_autodoc_typehints/__init__.py
src/sphinx_autodoc_typehints/attributes_patch.py
src/sphinx_autodoc_typehints/parser.py
tests/roots/test-dummy/dummy_module_future_annotations.py
tests/roots/test-dummy/dummy_module_simple_default_role.py
tests/roots/test-dummy/simple_default_role.rst
tests/test_sphinx_autodoc_typehints.py

Fixes #421, fixes https://github.com/scverse/scanpy/issues/2829
This PR introduces a `parse` function that abstracts away the instantiation and use of a `RSTParser` instance.
It uses the `sphinx.util.docutils:sphinx_domains` context manager to make sure that the `docutils` directive and role registries are managed properly.

Stop parsing from overwriting Sphinx configuration

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

Add option to force unions (and options) to be rendered with bars

---

README.md

Add missing option to readme

---

src/sphinx_autodoc_typehints/__init__.py
src/sphinx_autodoc_typehints/parser.py
tests/test_integration.py
tests/test_sphinx_autodoc_typehints.py

Resolves #444 and #425
Ignore the rst_epilog/rst_prolog during parsing type hints like #436 did. This still keeps the replacement behavior.
I tried adjusting the parsing, but the XML node line counting, and the list of lines given are too intertwined without rewriting it completely.
`test_sphinx_autodoc_typehints` was broken for me in Windows, so I have added an encoding kwarg for it to work.
EDIT: Working on making tests pass... and adding them.

Return injection fix

---

.pre-commit-config.yaml
pyproject.toml
src/sphinx_autodoc_typehints/__init__.py
tests/test_integration_autodoc_type_aliases.py

This PR addresses Issues #284.
Currently, `autodoc-typehints` does not honor the [`autodoc_type_aliases` configuration of `sphinx.ext.autodoc`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_type_aliases). For example,
```python
from numpy.typing import ArrayLike
def func(x: ArrayLike):...
```
renders
```rst
**func(x: _SupportsArray[dtype[Any]] |
_NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float |
complex | str | bytes | _NestedSequence[bool | int | float | complex |
str | bytes])
```
even if `autodoc_type_aliases = {'ArrayLike': 'ArrayLike'}` line in `conf.py`.
I modified `autodoc_typehints` to pass `app.config.autodoc_type_aliases` to `sphinx_signature()` calls to match `sphinx.ext.autodoc` and print the alias instead of the annotation …

Support autodoc_type_aliases configuration

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_integration.py
tests/test_integration_autodoc_type_aliases.py

This PR fixes the bugs introduced in v2.2:
* Error during checking for annotation alias (#462)
* Incorrect alias name look up (looking up alias name instead of the true type name)
* Aliased type ignored for the return type
The new alias look up mechanism follows closely as done in `sphinx.util.inspect.signature()`

Fix issue #462 and another alias processing bug

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_integration_issue_384.py

Here is another quick fix.
The fix advances the line to the last line of the last `:param:` paragraph by detecting either that the next line is empty or has no indentation and placing the default at the end of the last nonempty line.
I've read somewhere else that rst docstring spec does not explicitly mention anything about multiline argument descriptions, but I understand it is widely accepted to use hanging indentation.
@gaborbernat & @hoodmane - One thing I'm not sure of is the handling of a multi-paragraph `:param:` description. It is likely rare to document in such a way. But when it does, should the default be placed at the end of the first or the last paragraph? 
I've gone with the latter for now, but I can see myself preferring the default to appear on the first paragraph when it …

Fix for Issue #384: typehints_defaults = "braces-after" fails for a multiline `:param:` entry

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

It seems we brought in better sphinx types due to an upstream change?

Fix mypy errors due to unneeded type ignores

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_integration.py

We want to position our insertion before the directive but we incorrectly get a negative insertion line. This inserts at the end rather than at the beginning, and we fail to leave the correct empty line after the directive.
Resolves #467

Fix rendering when docstring starst with a directive

---

src/sphinx_autodoc_typehints/__init__.py
tests/roots/test-dummy/export_module.py
tests/roots/test-dummy/future_annotations.rst
tests/roots/test-dummy/simple.rst
tests/roots/test-dummy/simple_default_role.rst
tests/roots/test-dummy/simple_no_use_rtype.rst
tests/roots/test-dummy/without_complete_typehints.rst
tests/roots/test-dummy/wrong_module_path.py
tests/roots/test-dummy/wrong_module_path.rst
tests/test_integration.py
tests/test_sphinx_autodoc_typehints.py

This adds a configuration option that allows the user to rewrite module names if needed. Resolves #473. Note that we also rewrite the names of `_io` and `typing_extensions` internally. One benefit of this hook is that if other similar rewrites are needed, users will be able to immediately add them without having to patch sphinx_autodoc_typehints itself.
One disadvantage is that by default, having a function in the config prevents caching. I think this can be handled with the following slightly inelegant hack:
```py
class ModuleNameRewriteHook:
version: int
def __eq__(self, other):
return type(self) == type(other) and self.version == other.version
def __init__(self):
self.version = 2
def __call__(self, module):
return module
typehints_fixup_module_name = ModuleNameRewriteHook()
```
See …

Add module name rewrite configuration option

---

src/sphinx_autodoc_typehints/patches.py
tests/test_integration.py

Resolves #480. See upstream bug report here: https://sourceforge.net/p/docutils/patches/211/

Fix placement of return type when there is a doctest

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_integration.py

Apply typehints_formatter to signature

---

src/sphinx_autodoc_typehints/__init__.py

Fixes #454
Ref https://sourceforge.net/p/docutils/bugs/496.

🐛 Replace docutils private API use w/ public

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_sphinx_autodoc_typehints.py

Fixes #498
Also apparently the emitted role for `FunctionType` used to be wrong, so fixes that as well.

Fix roles for `types` module

---

.pre-commit-config.yaml
pyproject.toml
tests/test_integration.py
tests/test_sphinx_autodoc_typehints.py

This needs a few manual changes

Update Ruff to 0.9.1

---

README.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_integration.py

Don't add :rtype: None

---

src/sphinx_autodoc_typehints/__init__.py
tests/test_integration.py

Place rtype after directive

---

src/sphinx_autodoc_typehints/patches.py
tox.ini

Fix the CI failing due to type error

---

README.md
src/sphinx_autodoc_typehints/__init__.py
tests/test_integration.py

Add types and subtypes to all warnings logged with the Sphinx logger. This will let folks suppress each type of warning with the [suppress_warnings config option](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-suppress_warnings).
Continues the work that @aeisenbarth did in https://github.com/tox-dev/sphinx-autodoc-typehints/pull/433 to fix https://github.com/tox-dev/sphinx-autodoc-typehints/issues/432 .

Warning types and subtypes
