tox-dev/sphinx-autodoc-typehints

- sphinx_autodoc_typehints.py
> Resolve dotted attribute names - bugfix #34

- sphinx_autodoc_typehints.py
- tests/roots/test-dummy/dummy_module.py
- tests/test_sphinx_autodoc_typehints.py
> adding support for trailing underscores

- README.rst
- sphinx_autodoc_typehints.py
- tests/conftest.py
- tests/roots/test-dummy/dummy_module.py
- tests/roots/test-dummy/index.rst
- tests/test_sphinx_autodoc_typehints.py
> feat: Option to always document parameter types

- sphinx_autodoc_typehints.py
- tests/roots/test-dummy/dummy_module.py
- tests/test_sphinx_autodoc_typehints.py
> fix indent of multiline string

- setup.cfg
- sphinx_autodoc_typehints.py
- tests/test_sphinx_autodoc_typehints.py
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>
> Fix the CI and 3.10 regressions

- .github/workflows/check.yml
- pyproject.toml
- setup.cfg
- src/sphinx_autodoc_typehints/__init__.py
- tests/conftest.py
- tests/test_sphinx_autodoc_typehints.py
- tests/test_version.py
- tox.ini
- whitelist.txt
> Add type information and check via mypy

- CHANGELOG.md
- README.md
I’m sorry, I forgot to update the option name everywhere. And of course I only realize after I ask you to make a release. Sorry!
> Fix option name

- CHANGELOG.md
- README.md
- src/sphinx_autodoc_typehints/__init__.py
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>
> Remove set_type_checking flag

- CHANGELOG.md
- src/sphinx_autodoc_typehints/__init__.py
- tests/roots/test-resolve-typing-guard/demo_typing_guard.py
- tests/test_sphinx_autodoc_typehints.py
- whitelist.txt
> More robust handling of type guard imports

- .pre-commit-config.yaml
- CHANGELOG.md
- setup.cfg
- src/sphinx_autodoc_typehints/__init__.py
- tests/test_sphinx_autodoc_typehints.py
- whitelist.txt
> Handle ForwardRef, expand TypeVar and link Ellipsis

- src/sphinx_autodoc_typehints/__init__.py
> inspect.getsource can raise TypeError

- CHANGELOG.md
- setup.cfg
- src/sphinx_autodoc_typehints/__init__.py
- tests/test_sphinx_autodoc_typehints.py
- tox.ini
> Support and require nptyping 2

- .pre-commit-config.yaml
- pyproject.toml
- src/sphinx_autodoc_typehints/__init__.py
- tests/roots/test-dummy/dummy_module.py
- tests/test_sphinx_autodoc_typehints.py
> Fix IndexError for line and keyword split

- .pre-commit-config.yaml
- pyproject.toml
- src/sphinx_autodoc_typehints/__init__.py
- tox.ini
Committed via https://github.com/asottile/all-repos
> Bump deps and tools

- .github/workflows/check.yml
- tox.ini
Committed via https://github.com/asottile/all-repos
> Add 3.12 support

- .github/workflows/check.yml
- .github/workflows/release.yml
- pyproject.toml
- src/sphinx_autodoc_typehints/__init__.py
- tests/test_sphinx_autodoc_typehints.py
- tox.ini
Blocked on https://github.com/numpy/numpy/issues/23808
> Test against 3.12 beta 2

- src/sphinx_autodoc_typehints/__init__.py
- tests/roots/test-resolve-typing-guard/demo_typing_guard.py
- tests/roots/test-resolve-typing-guard/demo_typing_guard_dummy.py
- tests/test_sphinx_autodoc_typehints.py
> Fix type guard handling for classes

- src/sphinx_autodoc_typehints/__init__.py
- tests/test_integration.py
- tests/test_sphinx_autodoc_typehints.py
> FIX Put a slash space between xref and type args

- src/sphinx_autodoc_typehints/__init__.py
- tests/test_integration.py
> ENH Make types in signature respect `typehints_fully_qualified`

- .github/workflows/check.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/sphinx_autodoc_typehints/__init__.py
- src/sphinx_autodoc_typehints/patches.py
- tests/roots/test-resolve-typing-guard/demo_typing_guard.py
- tests/test_sphinx_autodoc_typehints.py
- tox.ini
> Support Sphinx 7.3 and drop 3.8 support

- src/sphinx_autodoc_typehints/patches.py
> Fix the type checker
